### ISSUE TITLE
Fabric version causes freeze on Preparing spawn area

### ISSUE THREAD

**Issue by d4rkm0nkey** [axelrindle/minecraft-chicken-drop-feathers#5]
I cloned the git repo and build the Fabric version with ./gradlew build and when I use the mod my Minecraft freezes on Preparing spawn area. When putting the mod on the server, nothing  happens, because the mixin is not injected. When I add the mixin to the server mixin "chickendropfeathersmod.mixins.json" The server freezes on Preparing spawn area as well.
This might be because of a conflict with another mod I have. I will test the mod without other mods now and try to figure out the problem.

**Comment by d4rkm0nkey** [comment]
I removed all my mods and started the game with only Modmenu, Fabric API and Chicken Drop Feathers.

I constantly get the warning:
Failed to create mob
```
java.lang.NoSuchFieldException: goalSelector
	at java.lang.Class.getField(Class.java:1703)
	at net.minecraft.class_1428.handler$zcf000$initGoals(class_1428.java:525)
	at net.minecraft.class_1428.method_5959(class_1428.java:66)
	at net.minecraft.class_1308.<init>(class_1308.java:140)
	at net.minecraft.class_1314.<init>(class_1314.java:12)
	at net.minecraft.class_1296.<init>(class_1296.java:28)
	at net.minecraft.class_1429.<init>(class_1429.java:39)
	at net.minecraft.class_1428.<init>(class_1428.java:49)
	at net.minecraft.class_1299.method_5883(class_1299.java:463)
	at net.minecraft.class_1948.method_8661(class_1948.java:499)
	at net.minecraft.class_3754.method_12107(class_3754.java:760)
	at net.minecraft.class_2806.method_16566(class_2806.java:107)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:263)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
And on closing the game I get a lot of those errors:
```
Error executing task on Server
java.lang.NoSuchFieldException: goalSelector
	at java.lang.Class.getField(Class.java:1703)
	at net.minecraft.class_1428.handler$zcf000$initGoals(class_1428.java:525)
	at net.minecraft.class_1428.method_5959(class_1428.java:66)
	at net.minecraft.class_1308.<init>(class_1308.java:140)
	at net.minecraft.class_1314.<init>(class_1314.java:12)
	at net.minecraft.class_1296.<init>(class_1296.java:28)
	at net.minecraft.class_1429.<init>(class_1429.java:39)
	at net.minecraft.class_1428.<init>(class_1428.java:49)
	at net.minecraft.class_1299.method_5883(class_1299.java:463)
	at net.minecraft.class_1299.method_5888(class_1299.java:332)
	at net.minecraft.class_1299.method_5899(class_1299.java:320)
	at net.minecraft.class_1299.method_5894(class_1299.java:311)
	at net.minecraft.class_1826.method_7884(class_1826.java:87)
	at net.minecraft.class_1799.method_7981(class_1799.java:227)
	at net.minecraft.class_3225.method_14262(class_3225.java:345)
	at net.minecraft.class_3244.method_12046(class_3244.java:1040)
	at net.minecraft.class_2885.method_12547(class_2885.java:36)
	at net.minecraft.class_2885.method_11054(class_2885.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by d4rkm0nkey** [comment]
hmm it's weird, because if I setup the project in vscode with ./gradlew vscode and debug it, it works fine, but if I build it and put it in my mod folder it gives me those errors.

**Comment by axelrindle** [comment]
Ah I see, thank you for testing. The field `goalSelector` is used for registering a new entity `Goal` (this was called `AI` in previous versions) that is responsible for dropping the feathers. Seems like you're using a version where the field has another name. I will investigate that!

**Comment by d4rkm0nkey** [comment]
I looked into your code and changed some stuff. Removed the accessor and now it is working and the game doesn't crash anymore. It is even working on my server. Shall I send you the code or do a merge request?

**Comment by axelrindle** [comment]
Awesome! Yes, please open a PR and I will review that.
